# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1088, 787)
        MainWindow.setStyleSheet("background-color:#22222e")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-51, -91, 1291, 481))
        self.frame.setStyleSheet("background-color: #fb5b5d")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(60, 90, 291, 81))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white\n"
"")
        self.label.setObjectName("label")
        self.input_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.input_1.setGeometry(QtCore.QRect(65, 420, 380, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.input_1.setFont(font)
        self.input_1.setStyleSheet("background-color: #22222e;\n"
"border: 2px solid #f66867;\n"
"border-radius: 30;\n"
"color: white")
        self.input_1.setText("")
        self.input_1.setAlignment(QtCore.Qt.AlignCenter)
        self.input_1.setObjectName("input_1")
        self.input_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.input_2.setGeometry(QtCore.QRect(65, 500, 380, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.input_2.setFont(font)
        self.input_2.setStyleSheet("background-color: #22222e;\n"
"border: 2px solid #f66867;\n"
"border-radius: 30;\n"
"color: white")
        self.input_2.setText("")
        self.input_2.setAlignment(QtCore.Qt.AlignCenter)
        self.input_2.setObjectName("input_2")
        self.input_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.input_3.setGeometry(QtCore.QRect(65, 580, 380, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.input_3.setFont(font)
        self.input_3.setStyleSheet("background-color: #22222e;\n"
"border: 2px solid #f66867;\n"
"border-radius: 30;\n"
"color: white")
        self.input_3.setText("")
        self.input_3.setAlignment(QtCore.Qt.AlignCenter)
        self.input_3.setObjectName("input_3")
        self.input_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.input_4.setGeometry(QtCore.QRect(65, 660, 380, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.input_4.setFont(font)
        self.input_4.setStyleSheet("background-color: #22222e;\n"
"border: 2px solid #f66867;\n"
"border-radius: 30;\n"
"color: white")
        self.input_4.setText("")
        self.input_4.setAlignment(QtCore.Qt.AlignCenter)
        self.input_4.setObjectName("input_4")
        self.Create_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Create_btn.setGeometry(QtCore.QRect(10, 730, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Create_btn.setFont(font)
        self.Create_btn.setStyleSheet("QPushButton {\n"
"color: white;\n"
"border: 2px solid #555;\n"
"border-radius: 20px;\n"
"border-style: outset;\n"
"background-color: #fb5b5d;\n"
"padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: #fb5b5d\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border-style: inset;\n"
"background: #fa4244\n"
"}")
        self.Create_btn.setFlat(False)
        self.Create_btn.setObjectName("Create_btn")
        self.Clear_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Clear_btn.setGeometry(QtCore.QRect(190, 730, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Clear_btn.setFont(font)
        self.Clear_btn.setStyleSheet("QPushButton {\n"
"color: white;\n"
"border: 2px solid #555;\n"
"border-radius: 20px;\n"
"border-style: outset;\n"
"background-color: #fb5b5d;\n"
"padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: #fb5b5d\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border-style: inset;\n"
"background: #fa4244\n"
"}")
        self.Clear_btn.setObjectName("Clear_btn")
        self.Random_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Random_btn.setGeometry(QtCore.QRect(370, 730, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Random_btn.setFont(font)
        self.Random_btn.setStyleSheet("QPushButton {\n"
"color: white;\n"
"border: 2px solid #555;\n"
"border-radius: 20px;\n"
"border-style: outset;\n"
"background-color: #fb5b5d;\n"
"padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: #fb5b5d\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border-style: inset;\n"
"background: #fa4244\n"
"}")
        self.Random_btn.setObjectName("Random_btn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "ОБХОД ГРАФА"))
        self.Create_btn.setText(_translate("MainWindow", "Create"))
        self.Clear_btn.setText(_translate("MainWindow", "Clear"))
        self.Random_btn.setText(_translate("MainWindow", "Random"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
