# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(491, 781)
        MainWindow.setMinimumSize(QtCore.QSize(491, 781))
        MainWindow.setMaximumSize(QtCore.QSize(492, 781))
        MainWindow.setStyleSheet("background-color:#22222e")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 555, 511))
        self.frame.setToolTip("")
        self.frame.setStyleSheet("background-color: #fb5b5d")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 0, 491, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("color: white\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(self.frame)
        self.tableWidget.setGeometry(QtCore.QRect(0, 50, 491, 380))
        self.tableWidget.setAutoFillBackground(False)
        self.tableWidget.setStyleSheet("QTableWidget::item{\n"
"background-color: white;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 3px;\n"
"border-color:green;\n"
"}\n"
"\n"
"\n"
"QTableWidget::item:selected{\n"
"background-color: red;\n"
"border-width: 2px;\n"
"border-radius: 3px;\n"
"border-color:blue;\n"
"color: green;\n"
"}\n"
"")
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(0, 431, 60, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(0, 480, 160, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.graphTravel = QtWidgets.QLabel(self.frame)
        self.graphTravel.setGeometry(QtCore.QRect(60, 431, 431, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.graphTravel.setFont(font)
        self.graphTravel.setObjectName("graphTravel")
        self.wayCount = QtWidgets.QLabel(self.frame)
        self.wayCount.setGeometry(QtCore.QRect(160, 480, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.wayCount.setFont(font)
        self.wayCount.setObjectName("wayCount")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 520, 471, 261))
        self.layoutWidget.setToolTip("")
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.input_1 = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.input_1.setFont(font)
        self.input_1.setToolTip("")
        self.input_1.setStyleSheet("background-color: #22222e;\n"
"border: 2px solid #f66867;\n"
"border-radius: 20;\n"
"color: white")
        self.input_1.setText("")
        self.input_1.setAlignment(QtCore.Qt.AlignCenter)
        self.input_1.setObjectName("input_1")
        self.verticalLayout.addWidget(self.input_1)
        self.input_2 = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.input_2.setFont(font)
        self.input_2.setStyleSheet("background-color: #22222e;\n"
"border: 2px solid #f66867;\n"
"border-radius: 20;\n"
"color: white")
        self.input_2.setText("")
        self.input_2.setAlignment(QtCore.Qt.AlignCenter)
        self.input_2.setObjectName("input_2")
        self.verticalLayout.addWidget(self.input_2)
        self.input_3 = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.input_3.setFont(font)
        self.input_3.setStyleSheet("background-color: #22222e;\n"
"border: 2px solid #f66867;\n"
"border-radius: 20;\n"
"color: white")
        self.input_3.setText("")
        self.input_3.setAlignment(QtCore.Qt.AlignCenter)
        self.input_3.setObjectName("input_3")
        self.verticalLayout.addWidget(self.input_3)
        self.input_4 = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.input_4.setFont(font)
        self.input_4.setStyleSheet("background-color: #22222e;\n"
"border: 2px solid #f66867;\n"
"border-radius: 20;\n"
"color: white")
        self.input_4.setText("")
        self.input_4.setAlignment(QtCore.Qt.AlignCenter)
        self.input_4.setObjectName("input_4")
        self.verticalLayout.addWidget(self.input_4)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Create_btn = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Create_btn.setFont(font)
        self.Create_btn.setStyleSheet("QPushButton {\n"
"color: white;\n"
"border: 2px solid #555;\n"
"border-radius: 15px;\n"
"border-style: outset;\n"
"background-color: #fb5b5d;\n"
"padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: #fb5b5d\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border-style: inset;\n"
"background: #fa4244\n"
"}")
        self.Create_btn.setFlat(False)
        self.Create_btn.setObjectName("Create_btn")
        self.horizontalLayout.addWidget(self.Create_btn)
        self.Clear_btn = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Clear_btn.setFont(font)
        self.Clear_btn.setStyleSheet("QPushButton {\n"
"color: white;\n"
"border: 2px solid #555;\n"
"border-radius: 15px;\n"
"border-style: outset;\n"
"background-color: #fb5b5d;\n"
"padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: #fb5b5d\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border-style: inset;\n"
"background: #fa4244\n"
"}")
        self.Clear_btn.setObjectName("Clear_btn")
        self.horizontalLayout.addWidget(self.Clear_btn)
        self.Random_btn = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Random_btn.setFont(font)
        self.Random_btn.setStyleSheet("QPushButton {\n"
"color: white;\n"
"border: 2px solid #555;\n"
"border-radius: 15px;\n"
"border-style: outset;\n"
"background-color: #fb5b5d;\n"
"padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: #fb5b5d\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border-style: inset;\n"
"background: #fa4244\n"
"}")
        self.Random_btn.setObjectName("Random_btn")
        self.horizontalLayout.addWidget(self.Random_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "ОБХОД ГРАФА"))
        self.label_2.setText(_translate("MainWindow", "Обход:"))
        self.label_3.setText(_translate("MainWindow", "Количество путей:"))
        self.graphTravel.setText(_translate("MainWindow", "----------------"))
        self.wayCount.setText(_translate("MainWindow", "-------------------------"))
        self.Create_btn.setText(_translate("MainWindow", "Create"))
        self.Clear_btn.setText(_translate("MainWindow", "Clear"))
        self.Random_btn.setText(_translate("MainWindow", "Random"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
